name: CI
on:
  push:
    branches:
      - master

jobs:
    deploy:
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Set up Rust
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            profile: minimal
            default: true
        - name: Build latest release
          run: cargo build --release
        - name: Delete
          uses: ame-yu/action-delete-latest-release@v2
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
        - name: Create release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: release
            release_name: release
            body: Release for UPR
            draft: false
            prerelease: false
        - name: Upload mdbook
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./target/release/mdbook
            asset_name: mdbook
            asset_content_type: application/exe
